<?php

/**
 * @file
 * Relative Paths to Absolute URLs
 *
 * Filter for converting relative paths to absolute URLs.
 *
 */

/**
 * Implementation of hook_filter().
 * @todo support for non pretty urls
 */
function rel_to_abs_filter($op, $delta = 0, $format = -1, $text = '', $cache_id = 0) {
  if ( ($op=='proccess' || $op=='prepare') && $text != '') {

    $lang = language_default();

    global $base_path;
    $text = preg_replace(
      '/(src|href)=(\'|")' . preg_quote($base_path, '/') . '/',
      '$1=$2'. url('<front>', array('absolute' => TRUE, 'language' => $lang)),
      $text
    );

    return $text;
  }
  elseif ($op === 'list') {
    return array(t('Relative Paths to Absolute URLs'));
  }
  elseif ($op === 'description') {
    return t('Filter for convertion of relative paths to absolute URLs');
  }
  elseif ($op === 'settings') {
    return array();
  }
  return $text;
}

