<?php


/**
 * @file
 * Provide utility for clone display.
 */

/**
 * Implementation of hook_forms().
 */
function views_clone_display_forms($form_id, $args) {
  if (stristr($form_id, 'views_ui_clone_display_form')) {
    $forms[$form_id] = array(
      'callback' => 'views_ui_clone_display_form',
      'callback arguments' => $args,
    );
    return $forms;
  }
}

/**
 * Implementation of hook_theme_registry_alter().
 */
function views_clone_display_theme_registry_alter(&$theme_registry) {
  $theme_registry['views_ui_edit_tab']['preprocess functions'][] = 'template_preprocess_views_ui_edit_tab_clone';
}

function template_preprocess_views_ui_edit_tab_clone(&$vars) {
  $view = $vars['view'];
  $display = $vars['display'];

  if (isset($vars['remove']) && $vars['remove']) {
    $form_state = array('view' => &$view, 'display_id' => $display->id, 'ajax' => FALSE);
    $vars['remove'] = '<div class="views-clone-display">'. drupal_build_form('views_ui_clone_display_form_'. $display->id, $form_state) .'</div>'. $vars['remove'];
  }
}

function views_ui_clone_display_form(&$form_state) {
  $form = array();

  $form['#view'] = $form_state['view'];
  $form['#display_id'] = $form_state['display_id'];
  $form['clone'] = array(
    '#type' => 'submit',
    '#value' => t('Clone'),
    '#submit' => array('views_clone_display_form_alter_clone_submit'),
  );

  return $form;
}

function views_clone_display_form_alter_clone_submit($form, &$form_state) {
  $view = $form['#view'];
  $display_id = $form['#display_id'];
  $display = db_fetch_object(db_query("SELECT * FROM {views_display} WHERE id='%s' AND vid=%d", $display_id, $view->vid));
  $new_position = db_result(db_query("SELECT COUNT(*) FROM {views_display} WHERE vid=%d", $view->vid));
  $new_position++;
  
  while (db_result(db_query("SELECT vid FROM {views_display} WHERE vid=%d AND position=%d", $view->vid, $position))) {
    $new_position++;
  }  

  $new_id_display = db_result(db_query("SELECT COUNT(*) FROM {views_display} WHERE vid=%d AND display_plugin='%s'", $view->vid, $display->display_plugin));
  $new_id_display++;

  while (db_result(db_query("SELECT vid FROM {views_display} WHERE vid=%d AND display_plugin='%s' AND id='%s'", $view->vid, $display->display_plugin, $display->display_plugin . '_'. $new_id_display))) {
    $new_id_display++;
  }

  $new_id_display = $display->display_plugin . '_'. $new_id_display;

  db_query("INSERT INTO {views_display} (vid, id, display_title, display_plugin, position, display_options) VALUES(%d, '%s', '%s', '%s', %d, '%s')", $display->vid, $new_id_display, $display->display_title, $display->display_plugin, $new_position, $display->display_options);
  drupal_set_message(t('Display @display clone successful', array('@display' => $display->display_title)), 'status');
}
