<?php

/**
 * @file
 * This is the module file. It contains hooks for panels and views.
 */

/**
 * Implementation of hook_views_api().
 */
function cache_actions_views_api() {
  return array(
    'api' => 2.0,
  );
}

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function cache_actions_ctools_plugin_directory($module, $plugin) {
  if (($module == 'page_manager' || $module == 'panels' || $module == 'ctools') && !empty($plugin)) {
    return "plugins/$plugin";
  }
}
