<?php

/**
 * Implementation of hook_uninstall().
 */
function module_filter_uninstall() {
  variable_del('module_filter_tabs');
}

/**
 * Force the menu system to rebuild.
 */
function module_filter_update_6000() {
  $ret = array();
  $ret[] = array('success' => TRUE, 'query' => t('Force menu to rebuild.'));
  return $ret;
}

/**
 * Delete variable 'module_filter_autocomplete'.
 */
function module_filter_update_6100() {
  variable_del('module_filter_autocomplete');
}
